server:
  port: 8083

spring:
  application:
    name: Utilisateur
  datasource:
    username: root
    password: amine1230
    url: jdbc:mysql://localhost:3306/Security?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

